language: python

sudo: false

dist: trusty

python:
- '3.5'

os:
- linux

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -U coveralls
  - pip install -U coverage
  - pip install -U pylint

before_script: # configure a headless display to test plot generation
- sudo apt-get install -y enchant
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
#- python -m coverage run --source . -m unittest discover --verbose
- "coverage run --source=ldt setup.py test"

after_success:
  - python -m pylint --load-plugins=pylint.extensions.mccabe --docstring-min-length 5 --no-docstring-rgx "^(test)?_|.*Tests$" --unsafe-load-any-extension y --output-format colorized  --reports y $(find . -name "*.py")
  - python -m coverage report --show-missing
  - coveralls